
services:
  nginx:
    ports:
    - "5000:80"
  node-backend:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_USER=ikhtiyor
      - MYSQL_PASSWORD=12345
      - SESSION_SECRET=bookstore_secret
    command: npm run dev
  
  mysql-db:
    environment:
      - MYSQL_ROOT_USER=ikhtiyor
      - MYSQL_ROOT_PASSWORD=12345
